version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo_dev
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_dev:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_dev
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_dev
    ports:
      - "${BACKEND_PORT}:3000"
    env_file: .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      NODE_ENV: development
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo_data_dev:
